# Generated by Django 3.0.5 on 2021-05-18 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athleteScheduling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='_partitionKey',
            field=models.CharField(default='masterSchedule', editable=False, max_length=14),
        ),
        migrations.AlterField(
            model_name='event',
            name='_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
