# Generated by Django 3.0.5 on 2021-05-18 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athleteScheduling', '0002_auto_20210518_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
